pdp/member/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'voir/(?P<user_name>.+)$', views.details),
    url(r'editer$', views.edit_profile),
    url(r'connexion$', views.login_view),
    url(r'inscription$', views.register_view),
    url(r'deconnexion/$', views.logout_view),
    url(r'$', views.index),
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

urlpatterns = patterns('',
    url(r'articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', pages.views.accueil),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/member/models.py
# coding: utf-8

from hashlib import md5

from django.db import models
from django.contrib.auth.models import User

from pdp.forum.models import Post, Topic
from pdp.tutorial.models import Tutorial
from pdp.article.models import Article


class Profile(models.Model):
    '''Represents an user profile'''
    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'

    user = models.ForeignKey(User, unique=True, verbose_name='Utilisateur')

    site = models.CharField('Site internet', max_length=128, blank=True)
    show_email = models.BooleanField('Afficher adresse mail publiquement',
                                     default=True)

    biography = models.TextField('Biographie', blank=True)

    def __unicode__(self):
        '''Textual forum of a profile'''
        return self.user.username

    def get_absolute_url(self):
        '''Absolute URL to the profile page'''
        return '/membres/voir/%s' % self.user.username

    def get_gravatar_url(self):
        '''Avatar URL (using Gravatar)'''
        return 'http://gravatar.com/avatar/%s?d=identicon' % md5(self.user.email).hexdigest()

    def get_post_count(self):
        '''Number of messages posted'''
        return Post.objects.all().filter(author__pk=self.user.pk).count()

    def get_topic_count(self):
        '''Number of threads created'''
        return Topic.objects.all().filter(author=self.user).count()

    # Tutorial

    def get_tutorials(self):
        return Tutorial.objects.filter(authors=self.user.pk)

    def get_visible_tutorials(self):
        return self.get_tutorials().filter(is_visible=True)

    def get_hidden_tutorials(self):
        return self.get_tutorials().filter(is_visible=False)

    # Article

    def get_articles(self):
        return Article.objects.all().filter(author=self.user)

    def get_visible_articles(self):
        return self.get_articles().filter(is_visible=True)

    def get_hidden_articles(self):
        return self.get_articles().filter(is_visible=False)

pdp/member/forms.py
# coding: utf-8

from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    email = forms.CharField()
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)
    show_email = forms.BooleanField(required=False)


class ProfileForm(forms.Form):
    biography = forms.CharField(required=False, widget=forms.Textarea)
    site = forms.CharField(required=False, max_length=128)
    show_email = forms.BooleanField(required=False)

pdp/member/views.py
# coding: utf-8

from django.shortcuts import redirect, get_object_or_404
from django.http import Http404

from django.contrib.auth.models import User, SiteProfileNotAvailable
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.core.context_processors import csrf

from pdp.utils.tokens import generate_token
from pdp.utils import render_template

from models import Profile
from forms import LoginForm, ProfileForm, RegisterForm


def index(request):
    '''Displays the list of registered users'''
    profiles = Profile.objects.all().order_by('user__date_joined')
    return render_template('member/index.html', {
        'profiles': profiles
    })


def details(request, user_name):
    '''Displays details about a profile'''
    usr = get_object_or_404(User, username=user_name)
    try:
        profile = usr.get_profile()
    except SiteProfileNotAvailable:
        raise Http404
    return render_template('member/profile.html', {
        'usr': usr, 'profile': profile
    })

@login_required
def edit_profile(request):
    try:
        profile_pk = int(request.GET['profil'])
    except KeyError:
        raise Http404
    profile = get_object_or_404(Profile, pk=profile_pk)
    # Making sure the user is allowed to do that
    if not request.user == profile.user:
        raise Http404
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            data = form.data
            profile.biography = data['biography']
            profile.site = data['site']
            profile.show_email = 'show_email' in data
            profile.save()
            return redirect(profile.get_absolute_url())
        else:
            raise Http404
    else:
        return render_template('member/edit_profile.html', {
            'profile': profile
        })

def login_view(request):
    csrf_tk = {}
    csrf_tk.update(csrf(request))

    error = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['get_token'] = generate_token()
                return redirect('/')
            else:
                error = 'Ce compte n\'est pas actif'
        else:
            error = 'Le couple pseudo/mot de passe est erroné'
    else:
        form = LoginForm()
    csrf_tk['error'] = error
    csrf_tk['form'] = form
    return render_template('member/login.html', csrf_tk)

@login_required
def logout_view(request):
    logout(request)
    request.session.clear()
    return redirect('/')

def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            data = form.data
            user = User.objects.create_user(
                data['username'],
                data['email'],
                data['password'])
            profile = Profile(user=user, show_email='show_email' in data)
            profile.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)
            return render_template('member/register_success.html')

    return render_template('member/register.html')

templates/member/edit_profile.html
{% extends "base.html" %}
{% load markup %}

{% block title %}
Éditer mon profil &ndash; Membres
{% endblock %}

{% block headline %}
Éditer mon profil
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/membres/">Membres</a> <span class="divider">/</span></li>
<li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a> <span class="divider">/</span></li>
<li class="active">Éditer mon profil</li>
{% endblock %}

{% block content %}

<form action="" method="POST" class="form-horizontal">

    <fieldset>
        <legend>Public</legend>

        <div class="control-group">
            <label for="id_biography" class="control-label">Biographie</label>
            <div class="controls">
                <textarea name="biography" class="input-block-level" rows="10" id="id_biography"
                    placeholder="Votre biographie au format Markdown.">{{ profile.biography }}</textarea>
            </div>
        </div>

        <div class="control-group">
            <label for="id_site" class="control-label">Site internet</label>
            <div class="controls">
                <input type="text" name="site" id="id_site" class="input-block-level"
                placeholder="Lien vers votre site internet personnel." value="{{ profile.site }}"/>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="show_email"
                    {% if profile.show_email %}checked{% endif %}>
                    Afficher mon adresse mail publiquement
                </label>
            </div>
        </div>

    </fieldset>

    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">
            <i class="icon-pencil icon-white"></i>
            Éditer
        </button>

        <a href="{{ profile.user.get_absolute_url }}" class="btn">
            Annuler
        </a>
    </div>

    {% csrf_token %}

</form>

{% endblock %}

templates/member/index.html
{% extends "base.html" %}

{% block title %}
Membres
{% endblock %}

{% block headline %}
Liste des membres
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li class="active">Membres</li>
{% endblock %}

{% block content %}

<p>
    Sur cette page vous pourrez trouver la liste des membres inscrits au site.
</p>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Pseudo</th>
            <th>Date d'inscription</th>
            <th>Dernière connexion</th>
        </tr>
    </thead>
    <tbody>
        {% for profile in profiles %}
        <tr>
            <td>
                <a href="{{ profile.get_absolute_url }}">
                    {{ profile.user.username }}</a>
            </td>
            <td>{{ profile.user.date_joined }}</td>
            <td>{{ profile.user.last_login }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/member/login.html
{% extends "base.html" %}

{% block title %}
Connexion &ndash; Membres
{% endblock %}

{% block headline %}
Se connecter
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/membres/">Membres</a> <span class="divider">/</span></li>
<li class="active">Connexion</li>
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}

    {% if error %}
        {{ error }}
    {% endif %}

    Si vous n'avez pas de compte, vous pouvez <a href="{% url pdp.member.views.register_view %}" >vous inscrire</a>.

    <form method="post" action="{% url pdp.member.views.login_view %}" class="form-horizontal">
        <fieldset>
            <legend>Identification</legend>
            <div class="control-group">
                <label class="control-label" for="id_username">Identifiant</label>
                <div class="controls">
                    <input type="text" name="username" id="id_username" maxlength="30" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="id_password">Mot magique</label>
                <div class="controls">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                </div>
            </div>
        </fieldset>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">
                Se connecter
            </button>
            <a href="/" class="btn">
                Annuler
            </a>
        </div>

        {% csrf_token %}
    </form>

{% else %}

Vous êtes déjà connecté

{% endif %}

{% endblock %}

templates/member/profile.html
{% extends "base.html" %}
{% load markup %}
{% load humane_date %}

{% block title %}
{{ usr.username }} &ndash; Membres
{% endblock %}

{% block headline %}
Profil de {{ usr.username }}
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/membres/">Membres</a> <span class="divider">/</span></li>
<li class="active">{{ usr.username }}</li>
{% endblock %}

{% block content %}

{% ifequal profile.user user %}
<p>
<a href="/membres/editer?profil={{ profile.pk }}" class="btn">
    <i class="icon-pencil"></i>
    Éditer mon profil
</a>
</p>
{% endifequal %}

<ul class="nav nav-tabs">
    <li class="active"><a href="#general" data-toggle="tab">Informations générales</a></li>
    <li {% if not profile.biography %}class="disabled"{% endif %}><a {% if profile.biography %}href="#bio" data-toggle="tab"{% endif %}>Biographie</a></li>
    <li><a href="#stats" data-toggle="tab">Statistiques</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane row active" id="general">
        <div class="span2">
            <img src="{{ profile.get_gravatar_url }}&amp;s=140" alt="Avatar" class="img-polaroid"/><br />
        </div>

        <div class="span10">
            <div class="spacer2"></div>
            <p>
                <span style="font-size: 300%;">
                    {{ usr.username }}
                </span>
            </p>
            <p>
                {% if profile.show_email %}
                <span class="muted">Adresse mail | </span> {{ usr.email }}<br />
                {% endif %}

                <span class="muted">Site internet | </span>
                    {% if profile.site %}
                    <a href="{{ profile.site }}">{{ profile.site }}</a>
                    {% else %}
                    aucun
                    {% endif %}
                    <br />

                <span class="muted">Date d'inscription |</span> {{ usr.date_joined|humane_date }}<br />
                <span class="muted">Dernière connexion |</span> {{ usr.last_login|humane_date }}
            </p>
        </div>
    </div>

    {% if profile.biography %}

    <div class="tab-pane" id="bio">
        {{ profile.biography|markdown:"safe,codehilite,extra" }}
    </div>

    {% endif %}

    <div class="tab-pane" id="stats">

        <div class="row-fluid">
            <div class="span4">
                <h3>Sur les forums</h3>
                <span class="pull-right">{{ profile.get_post_count }}</span>Messages postés<br />
                <span class="pull-right">{{ profile.get_topic_count }}</span>Sujets créés
            </div>

            <div class="span4">
                <h3>Dans les tutoriels</h3>
                <span class="pull-right">{{ profile.get_visible_tutorials.count }}</span>Tutoriels en ligne<br />
                <span class="pull-right">{{ profile.get_hidden_tutorials.count }}</span>Tutoriels en cours de rédaction<br />
                <span class="pull-right">{{ profile.get_tutorials.count }}</span>Total
            </div>

            <div class="span4">
                <h3>Et les articles</h3>
                <span class="pull-right">{{ profile.get_visible_articles.count }}</span>Articles en ligne<br />
                <span class="pull-right">{{ profile.get_hidden_articles.count }}</span>Articles en cours de rédaction <br />
                <span class="pull-right">{{ profile.get_articles.count }}</span>Total
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/member/register.html
{% extends "base.html" %}

{% block title %}
S'incrire &ndash; Membres
{% endblock %}

{% block headline %}
S'inscrire
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/membres/">Membres</a> <span class="divider">/</span></li>
<li class="active">S'inscrire</li>
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}

    {% if error %}
        {{ error }}
    {% endif %}

    <p>
    Vous êtes sur le point de vous inscrire sur Progdupeupl. Merci de
    fournir les informations nécessaires dans le formulaire suivant afin de
    poursuivre votre inscription.
    </p>

    <form method="post" action="{% url pdp.member.views.register_view %}"
        class="form-horizontal">

    <fieldset>    
        <legend>Identifiants</legend>
        <div class="control-group">
            <label class="control-label" for="id_email">Adresse mail</label>
            <div class="controls">
                <input type="text" name="email" id="id_email" class="popover-input"
                    data-content="Veuillez utiliser une adresse mail valide (votre image de profil sera basée sur l'image Gravatar associée à cette adresse)." />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_username">Nom d'utilisateur</label>
            <div class="controls">
                <input type="text" name="username" id="id_username" class="popover-input success"
                    data-content="Le nom unique qui vous identifiera sur le site." />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_password">Mot de passe</label>
            <div class="controls">
                <input type="password" name="password" id="id_password"/>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_password_match">Confirmation</label>
            <div class="controls">
                <input type="password" name="password_match" id="id_password_match" />
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Options</legend>
        <p>
            Ces options seront modifiables plus tard dans l'interface de
            gestion de votre profil si vous le désirez.
        </p>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="show_email"/>Afficher mon adresse mail publiquement
                </label>
            </div>
    </fieldset>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            Valider l'inscription
        </button>
        <a href="#" class="btn">Annuler</a>
    </div>

{% csrf_token %}
</form>

{% else %}

Vous êtes déjà connecté

{% endif %}

{% endblock %}

{% block js %}
<script type="text/javascript">
    $('.popover-input').popover({trigger: 'focus', title: 'Aide'});
</script>
{% endblock %}

templates/member/register_success.html
{% extends "base.html" %}

{% block title %}
Inscription réussie
{% endblock %}

{% block headline %}
Inscription réussie
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/membres/">Membres</a> <span class="divider">/</span></li>
<li class="active">Inscription</li>
{% endblock %}

{% block content %}

<p>
Vous avez bien été inscrit au site. <a href="{% url pdp.member.views.details user.username %}">Voir votre profil</a>.
</p>

{% endblock %}