pdp/forum/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    # Viewing a thread
    url(r'sujet/nouveau$', views.new),
    url(r'sujet/editer$', views.edit),
    url(r'sujet/(?P<topic_pk>\d+)-(?P<topic_slug>.+)$', views.topic),

    url(r'message/editer$', views.edit_post),
    url(r'message/nouveau$', views.answer),
    url(r'message/utile$', views.useful_post),

    # Forum details
    url(r'(?P<cat_slug>.+)/(?P<forum_pk>\d+)-(?P<forum_slug>.+)/$', views.details),

    # Forums belonging to one category
    url(r'(?P<cat_pk>\d+)-(?P<cat_slug>.+)/$', views.cat_details),

   # Home
   url(r'$', views.index),
)

pdp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

import pages.views
import settings

urlpatterns = patterns('',
    url(r'articles/', include('pdp.article.urls')),
    url(r'^tutoriels/', include('pdp.tutorial.urls')),
    url(r'^forums/', include('pdp.forum.urls')),
    url(r'^membres/', include('pdp.member.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', pages.views.accueil),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

pdp/forum/models.py
# coding: utf-8

from math import ceil

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

from pdp.utils import get_current_user

POSTS_PER_PAGE = 10

class Category(models.Model):
    '''A category, containing forums'''
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'

    title = models.CharField('Titre', max_length=80)

    def __unicode__(self):
        '''Textual form of a category'''
        return self.title

    def get_absolute_url(self):
        return '/forums/%s-%s/' % (self.pk, slugify(self.title))

    def get_forums(self):
        return Forum.objects.all().filter(category=self)


class Forum(models.Model):
    '''A forum, containing threads'''
    class Meta:
        verbose_name = 'Forum'
        verbose_name_plural = 'Forums'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    category = models.ForeignKey(Category, verbose_name='Catégorie')

    def __unicode__(self):
        '''Textual form of a forum'''
        return self.title

    def get_absolute_url(self):
        return '/forums/%s-%s/%s-%s/' % (
            self.category.pk,
            slugify(self.category.title),
            self.pk,
            slugify(self.title),
        )

    def get_topic_count(self):
        '''Gets the number of threads in the forum'''
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_last_message(self):
        '''Gets the last message on the forum, if there are any'''
        try:
            return Post.objects.all().filter(topic__forum__pk=self.pk).order_by('-pubdate')[0]
        except IndexError:
            return None


class Topic(models.Model):
    '''A thread, containing posts'''
    class Meta:
        verbose_name = 'Sujet'
        verbose_name_plural = 'Sujets'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    forum = models.ForeignKey(Forum, verbose_name='Forum')
    author = models.ForeignKey(User, verbose_name='Auteur')
    last_message = models.ForeignKey('Post', null=True, related_name='last_message', verbose_name='Dernier message')
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)

    is_solved = models.BooleanField('Est résolu')
    is_locked = models.BooleanField('Est verrouillé')
    is_sticky = models.BooleanField('Est en post-it')

    def __unicode__(self):
        '''Textual form of a thread'''
        return self.title

    def get_absolute_url(self):
        return '/forums/sujet/%s-%s' % (self.pk, slugify(self.title))

    def get_post_count(self):
        '''Gets the number of posts in the thread'''
        return Post.objects.all().filter(topic__pk=self.pk).count()

    def get_last_answer(self):
        '''Gets the last answer in the thread, if there are any'''
        try:
            return Post.objects.all().filter(topic__pk=self.pk).order_by('-pubdate')[0]
        except IndexError:
            return None

    def first_post(self):
        return Post.objects.filter(topic=self)[0]

    def last_read_post(self):
        try:
            return TopicRead.objects\
                .select_related()\
                .filter(topic=self, user=get_current_user())\
                .latest('post__pubdate').post
        except Post.DoesNotExist:
            return self.first_post()


class Post(models.Model):
    '''A forum post'''
    topic = models.ForeignKey(Topic, verbose_name='Sujet')
    author = models.ForeignKey(User, verbose_name='Auteur')
    text = models.TextField('Texte')

    pubdate = models.DateTimeField('Date de publication', auto_now_add=True)
    update = models.DateTimeField('Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField('Position dans le sujet')

    is_useful = models.BooleanField('Est utile', default=False)

    def __unicode__(self):
        '''Textual form of a post'''
        return u'<Post pour %s, %s>' % (self.topic, self.pk)

    def get_absolute_url(self):
        page = int(ceil(float(self.position_in_topic) / POSTS_PER_PAGE))

        return '%s?page=%s#p%s' % (self.topic.get_absolute_url(), page, self.pk)


class TopicRead(models.Model):
    topic = models.ForeignKey(Topic)
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)


def never_read(topic):
    return TopicRead.objects\
        .filter(post=topic.last_message, topic=topic, user=get_current_user())\
        .count() == 0


def mark_read(topic):
    TopicRead.objects.filter(topic=topic, user=get_current_user()).delete()
    t = TopicRead(
        post=topic.last_message, topic=topic, user=get_current_user())
    t.save()

pdp/forum/forms.py
# coding: utf-8

from django import forms

class TopicForm(forms.Form):
    title = forms.CharField(max_length=80)
    subtitle = forms.CharField(max_length=255, required=False)
    text = forms.CharField(widget=forms.Textarea)

class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

pdp/forum/views.py
# coding: utf-8

from datetime import datetime

from django.shortcuts import redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from pdp.utils import render_template, slugify

from models import Category, Forum, Topic, Post, POSTS_PER_PAGE
from models import never_read, mark_read
from forms import TopicForm, PostForm


def index(request):
    '''Display the category list'''
    categories = Category.objects.all()

    return render_template('forum/index.html', {
        'categories': categories
    })


def details(request, cat_slug, forum_pk, forum_slug):
    '''Display the given forum's thread list'''
    forum = get_object_or_404(Forum, pk=forum_pk)

    topics = Topic.objects.all()\
        .filter(forum__pk=forum.pk)\
        .order_by('-is_sticky', '-last_message__pubdate')

    # Check link
    if not cat_slug == slugify('%s-%s' % (forum.category.pk, forum.category.title))\
            or not forum_slug == slugify(forum.title):
        return redirect(forum.get_absolute_url())

    return render_template('forum/details.html', {
        'forum': forum, 'topics': topics
    })


def cat_details(request, cat_pk, cat_slug):
    '''Display the forums belonging to the given category'''
    category = get_object_or_404(Category, pk=cat_pk)
    forums = Forum.objects.all().filter(category__pk=category.pk)

    # Check link
    if not cat_slug == slugify(category.title):
        return redirect(category.get_absolute_url())

    return render_template('forum/cat_details.html', {
        'category': category, 'forums': forums
    })


def topic(request, topic_pk, topic_slug):
    '''Display a thread and its posts'''

    # TODO: Clean that up
    g_topic = get_object_or_404(Topic, pk=topic_pk)

    # Check link
    if not topic_slug == slugify(g_topic.title):
        return redirect(g_topic.get_absolute_url())

    if request.user.is_authenticated():
        if never_read(g_topic):
            mark_read(g_topic)

    posts = Post.objects.all().filter(topic__pk=g_topic.pk).order_by('position_in_topic')

    # Handle pagination
    paginator = Paginator(posts, POSTS_PER_PAGE)

    # The category list is needed to move threads
    categories = Category.objects.all()

    try:
        page_nbr = int(request.GET['page'])
    except KeyError:
        page_nbr = 1

    try:
        posts = paginator.page(page_nbr)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        raise Http404

    res = []
    if page_nbr != 1:
        # Show the last post of the previous page
        last_page = paginator.page(page_nbr - 1).object_list
        last_post = (last_page)[len(last_page) - 1]
        res.append(last_post)

    for post in posts:
        res.append(post)

    return render_template('forum/topic.html', {
        'topic': g_topic, 'posts': res, 'categories': categories,
        'pages': range(1, paginator.num_pages + 1), 'nb': page_nbr,
    })


@login_required
def new(request):
    '''Creates a new thread'''
    try:
        forum_pk = request.GET['forum']
    except KeyError:
        raise Http404

    forum = get_object_or_404(Forum, pk=forum_pk)

    if request.method == 'POST':
        # If the client is using the "preview" button
        if 'preview' in request.POST:
            return render_template('forum/new.html', {
                'forum': forum,
                'title': request.POST['title'],
                'subtitle': request.POST['subtitle'],
                'text': request.POST['text'],
            })

        form = TopicForm(request.POST)
        if form.is_valid():
            data = form.data
            # Creating the thread
            n_topic = Topic()
            n_topic.forum = forum
            n_topic.title = data['title']
            n_topic.subtitle = data['subtitle']
            n_topic.pubdate = datetime.now()
            n_topic.author = request.user
            n_topic.save()

            # Adding the first message
            post = Post()
            post.topic = n_topic
            post.author = request.user
            post.text = data['text']
            post.pubdate = datetime.now()
            post.position_in_topic = 1
            post.save()

            n_topic.last_message = post
            n_topic.save()

            return redirect(n_topic.get_absolute_url())

        else:
            # TODO: add errors to the form and return it
            raise Http404

    else:

        form = TopicForm()
        return render_template('forum/new.html', {
            'form': form, 'forum': forum
        })


@login_required
def edit(request):
    '''Edit the given thread'''
    if not request.method == 'POST':
        raise Http404

    try:
        topic_pk = request.POST['topic']
    except KeyError:
        raise Http404

    data = request.POST

    g_topic = get_object_or_404(Topic, pk=topic_pk)

    if not request.user == g_topic.author and not request.user.is_staff:
        return Http404

    if 'solved' in data:
        g_topic.is_solved = not g_topic.is_solved
    elif request.user.is_staff:
        if 'lock' in data:
            g_topic.is_locked = not g_topic.is_locked
        elif 'sticky' in data:
            g_topic.is_sticky = not g_topic.is_sticky
        elif 'follow' in data:
            raise NotImplementedError
        elif 'move' in data:
            try:
                forum_pk = int(request.POST['move_target'])
            except KeyError:
                raise Http404

            forum = get_object_or_404(Forum, pk=forum_pk)
            g_topic.forum = forum
        else:
            # The admin task doesn't exist
            raise Http404
    else:
        # The user task doesn't exist
        raise Http404

    g_topic.save()
    return redirect(g_topic.get_absolute_url())


@login_required
def answer(request):
    '''Adds an answer to a thread'''
    try:
        topic_pk = request.GET['sujet']
    except KeyError:
        raise Http404

    g_topic = get_object_or_404(Topic, pk=topic_pk)

    # Making sure posting is allowed
    if g_topic.is_locked:
        raise Http404

    # If we just sent data
    if request.method == 'POST':

        # Using the "preview" button or the "more options" button
        if 'preview' in request.POST or 'plus' in request.GET:
            text = request.POST['text']
            return render_template('forum/answer.html', {
                'text': text, 'topic': g_topic
            })

        # Saving the message
        else:
            form = PostForm(request.POST)
            if form.is_valid():
                data = form.data

                post = Post()
                post.topic = g_topic
                post.author = request.user
                post.text = data['text']
                post.pubdate = datetime.now()
                post.position_in_topic = g_topic.get_post_count() + 1
                post.save()

                g_topic.last_message = post
                g_topic.save()

                return redirect(post.get_absolute_url())
            else:
                raise Http404

    else:
        text = ''

        # Using the quote button
        if 'cite' in request.GET:
            post_cite_pk = request.GET['cite']
            post_cite = Post.objects.get(pk=post_cite_pk)

            for line in post_cite.text.splitlines():
                text = text + '> ' + line + '\n'

            text = u'**%s a écrit :**\n%s\n' % (
                post_cite.author.username, text)

        return render_template('forum/answer.html', {
            'topic': g_topic, 'text': text
        })


@login_required
def edit_post(request):
    try:
        post_pk = request.GET['message']
    except KeyError:
        raise Http404

    post = get_object_or_404(Post, pk=post_pk)

    g_topic = None
    if post.position_in_topic == 1:
        g_topic = get_object_or_404(Topic, pk=post.topic.pk)

    # Making sure the user is allowed to do that
    if post.author != request.user and not request.user.is_staff:
        raise Http404

    if request.method == 'POST':

        # Using the preview button
        if 'preview' in request.POST:
            if g_topic:
                g_topic = Topic(title=request.POST['title'], subtitle=request.POST['subtitle'])
            return render_template('forum/edit_post.html', {
                'post': post, 'topic': g_topic, 'text': request.POST['text'],
            })

        # The user just sent data, handle them
        post.text = request.POST['text']
        post.update = datetime.now()
        post.save()

        # Modifying the thread info
        if g_topic:
            g_topic.title = request.POST['title']
            g_topic.subtitle = request.POST['subtitle']
            g_topic.save()

        return redirect(post.get_absolute_url())

    else:
        return render_template('forum/edit_post.html', {
            'post': post, 'topic': g_topic, 'text': post.text
        })


@login_required
def useful_post(request):
    '''Marks a message as useful (for the OP)'''
    try:
        post_pk = request.GET['message']
    except KeyError:
        raise Http404

    post = get_object_or_404(Post, pk=post_pk)

    # Making sure the user is allowed to do that
    if post.author == request.user or request.user != post.topic.author:
        raise Http404

    post.is_useful = not post.is_useful
    post.save()

    return redirect(post.get_absolute_url())

templates/forum/answer.html
{% extends "base.html" %}
{% load markup %}

{% block title %}
Répondre au sujet &ndash; Forums
{% endblock %}

{% block headline %}
Répondre au sujet
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/forums/">Forums</a> <span class="divider">/</span></li>
<li><a href="{{ topic.forum.category.get_absolute_url }}">{{ topic.forum.category.title }}</a> <span class="divider">/</span></li>
<li><a href="{{ topic.forum.get_absolute_url }}">{{ topic.forum.title }}</a> <span class="divider">/</span></li>
<li><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a> <span class="divider">/</span></li>
<li class="active">Répondre au sujet</li>
{% endblock %}

{% block content %}
<form action="/forums/message/nouveau?sujet={{ topic.pk }}" method="POST">

    {% include "markdown-buttons.html" %}

    <textarea class="input-block-level" name="text" rows="20" id="id_text"
        placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>

    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">
            <i class="icon-ok icon-white"></i>
            Répondre
        </button>

        <button type="submit" name="preview" class="btn">
            <i class="icon-eye-open"></i>
            Prévisualisation
        </button>

        <a href="{{ topic.get_absolute_url }}" class="btn">
            <i class="icon-remove"></i>
            Annuler
        </a>
    </div>

    {% csrf_token %}
</form>

{% if text %}
<div class="well">
    <p style="text-align: center;">
        <b>Prévisualisation de votre message</b>
    </p>
    {{ text|markdown:"safe,codehilite,extra" }}
</div>
{% endif %}

{% endblock %}

templates/forum/cat_details.html
{% extends "base.html" %}

{% block title %}
{{ category.title }} &ndash; Forums
{% endblock %}

{% block headline %}
{{ category.title }}
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/forums/">Forums</a> <span class="divider">/</span></li>
<li class="active">{{ category.title }}</li>
{% endblock %}

{% block content %}

<p>
<a href=".." class="btn">Liste des forums</a>
</p>

<p>
Forums dans la catégorie sélectionnée :
</p>

{% include "forum/forums_common.html" %}

{% endblock %}

templates/forum/details.html
{% extends "base.html" %}
{% load humane_date %}

{% block title %}
{{ forum.title }} &ndash; Forums
{% endblock %}

{% block headline %}
{{ forum.title }} <br /><small>{{ forum.subtitle }}</small>
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/forums/">Forums</a> <span class="divider">/</span></li>
<li><a href="{{ forum.category.get_absolute_url }}">{{ forum.category.title }}</a> <span class="divider">/</span></li>
<li class="active">{{ forum.title }}</li>
{% endblock %}

{% block content %}

<div class="pull-right">
{% if user.is_authenticated %}
<a href="/forums/sujet/nouveau?forum={{ forum.pk }}" class="btn">
    <i class="icon-plus"></i>
    Nouveau
</a>
{% endif %}
</div>

<p>
    <a href="../.." class="btn">Liste des forums</a>
</p>

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th class="span1">Statut</th>
            <th class="span5">Sujet</th>
            <th class="span1">Auteur</th>
            <th class="span1">Réponses</th>
            <th class="span4">Dernière réponse</th>
        </tr>
    </thead>
    <tbody>
        {% for topic in topics %}
        <tr class="{% if topic.is_solved %}success{% endif %}">
            <td style="text-align: center; vertical-align: middle;">
                {% if topic.is_sticky %}
                <i class="icon-bookmark" title="Ce sujet est épinglé"></i>
                {% endif %}
                {% if topic.is_locked %}
                <i class="icon-lock" title="Ce sujet est verrouillé"></i>
                {% endif %}
                {% if topic.is_solved %}
                <i class="icon-ok" title="Ce sujet est résolu"></i>
                {% endif %}

                {% if user.is_authenticated %}
                    {% with topic.last_read_post as last_read_post %}
                    {% ifnotequal last_read_post topic.get_last_answer %}
                        <i class="icon-exclamation-sign"></i>
                    {% endifnotequal %}
                    {% endwith %}
                {% endif %}
            </td>
            <td>
                <a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a>
                <br />{{ topic.subtitle }}
            </td>
            <td>
                <a href="{{ topic.author.get_absolute_url }}">
                    {{ topic.author.username }}</a>
            </td>
            <td>
                {{ topic.get_post_count|add:"-1" }}
            </td>
            <td>
                {% if topic.get_last_answer %}
                    <a href="{{ topic.get_last_answer.get_absolute_url }}">
                        {{ topic.get_last_answer.pubdate|humane_date }}
                    </a>
                    par
                    <a href="{{ topic.get_last_answer.author.get_absolute_url }}">
                        {{ topic.get_last_answer.author.username }}
                    </a>
                {% else %}
                    Aucune
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/forum/edit_post.html
{% extends "base.html" %}
{% load markup %}

{% block title %}
Éditer un message &ndash; Forums
{% endblock %}

{% block headline %}
Éditer un message
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/forums/">Forums</a><span class="divider">/</span></li>
<li><a href="{{ post.topic.forum.category.get_absolute_url }}">{{ post.topic.forum.category.title }}</a> <span class="divider">/</span></li>
<li><a href="{{ post.topic.forum.get_absolute_url }}">{{ post.topic.forum.title }}</a> <span class="divider">/</span></li>
<li><a href="{{ post.topic.get_absolute_url }}">{{ post.topic.title }}</a> <span class="divider">/</span></li>
<li class="active">Éditer un message</li>
{% endblock %}

{% block content %}
<form action="" method="POST" class="form-horizontal">
    {% if topic %}
    <fieldset>
        <legend>Sujet</legend>
        <div class="control-group">
            <label class="control-label" for="id_title">Titre</label>
            <div class="controls">
                <input type="text" name="title" id="id_title"
                    value="{{ topic.title }}" />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="id_subtitle">Sous titre</label>
            <div class="controls">
                <input type="text" name="subtitle" id="id_subtitle"
                    value="{{ topic.subtitle }}" />
            </div>
        </div>
    </fieldset>
    {% endif %}
    <fieldset>
        <legend>Message</legend>
        <div class="control-group">
            <label class="control-label" for="id_text">Texte</label>
            <div class="controls">
                {% include "markdown-buttons.html" %}
                <textarea id="id_text" name="text"
                    class="input-block-level" rows="20">{{ text }}</textarea>
            </div>
        </div>
    </fieldset>

    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">
            <i class="icon-pencil icon-white"></i>
            Éditer
        </button>

        <button type="submit" name="preview" class="btn">
            <i class="icon-eye-open"></i>
            Prévisualisation
        </button>

        <a href="{{ post.get_absolute_url }}" class="btn">Annuler</a>
    </div>

    {% csrf_token %}
</form>

<div class="well">
    <p style="text-align: center;">
        <b>Prévisualisation de votre message</b>
    </p>
    {{ text|markdown:"safe,codehilite,extra" }}
</div>

{% endblock %}

templates/forum/forums_common.html
{# Block displaying the list of forums belonging to a category #}
{% load humane_date %}

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th class="span1">Statut</th>
            <th class="span5">Titre</th>
            <th class="span1">Sujets</th>
            <th class="span5">Dernier message</th>
        </tr>
    </thead>

    <tbody>
    {% for forum in category.get_forums %}
    <tr>
        <td>
        </td>
        <td>
            <a href="{{ forum.get_absolute_url }}">{{ forum.title }}</a><br />
            {{ forum.subtitle }}
        </td>
        <td>
            {{ forum.get_topic_count }}
        </td>
        <td>
            {% if forum.get_last_message %}
            Posté
            <a href="{{ forum.get_last_message.get_absolute_url }}">
                {{ forum.get_last_message.pubdate|humane_date }}
            </a>
            par
            <a href="{{ forum.get_last_message.author.get_absolute_url }}">
                {{ forum.get_last_message.author.username }}
            </a>
            dans
            <a href="{{ forum.get_last_message.topic.get_absolute_url }}">
                {{ forum.get_last_message.topic.title }}
            </a>
            {% else %}
            Aucun message
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

templates/forum/index.html
{% extends "base.html" %}
{% block title %}
Forums
{% endblock %}

{% block headline %}
Liste des forums
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li class="active">Forums</li>
{% endblock %}

{% block content %}

<p>
Voici la liste des forums mis à votre disposition pour échanger avec le reste
de la communauté, rangés par thématiques.
</p>

{% for category in categories %}

<h2>
    <a href="{{ category.get_absolute_url }}">
        {{ category.title }}</a>
</h2>

{% include "forum/forums_common.html" %}

{% endfor %}

{% endblock %}

templates/forum/new.html
{% extends "base.html" %}
{% load markup %}

{% block title %}
Nouveau sujet &ndash; Forums
{% endblock %}

{% block headline %}
Nouveau sujet
{% endblock %}

{% block breadcrumb %}
<li><a href="/">Accueil</a> <span class="divider">/</span></li>
<li><a href="/forums/">Forums</a> <span class="divider">/</span></li>
<li><a href="{{ forum.category.get_absolute_url }}">{{ forum.category.title }}</a> <span class="divider">/</span></li>
<li><a href="{{ forum.get_absolute_url }}">{{ forum.title }}</a> <span class="divider">/</span></li>
<li class="active">Nouveau sujet</li>
{% endblock %}

{% block content %}
<form action="" method="POST">

    <input type="text" placeholder="Titre" name="title" value="{{ title }}" /><br />
    <input type="text" placeholder="Sous-titre" name="subtitle" value="{{ subtitle }}" /><br />

    {% include "markdown-buttons.html" %}
    
    <textarea class="input-block-level" rows="20" name="text" id="id_text"
        placeholder="Contenu au format Markdown.">{{ text }}</textarea>

    <div style="text-align: center;">
        <button type="submit" class="btn btn-primary">
            <i class="icon-plus icon-white"></i>
            Nouveau sujet
        </button>

        <button type="submit" name="preview" class="btn">
            <i class="icon-eye-open"></i>
            Prévisualiation
        </button>

        <a href="{{ forum.get_absolute_url }}" class="btn">
            Retour
        </a>
    </div>

    {% csrf_token %}
</form>

{% if text %}
<div class="well">
    <p style="text-align: center;">
        <b>Prévisualisation de votre message</b>
    </p>
    {{ text|markdown:"safe,codehilite,extra" }}
</div>
{% endif %}

{% endblock %}